[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
fs_permissions = [
  { access = "read-write", path = "./addresses.json" },
  { access = "read-write", path = "./out" },
]

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
mainnet2 = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism2 = "https://optimism-mainnet.infura.io/v3/${INFURA_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum2 = "https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}"

sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia2 = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
holesky = "https://eth-holesky.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
holesky2 = "https://ethereum-holesky.publicnode.com"
anvil = "http://127.0.0.1:8545"

[etherscan]
mainnet = {key = "${ETHERSCAN_API_KEY_ETHEREUM}"}
arbitrum = {key = "${ETHERSCAN_API_KEY_ARBITRUM }"}
optimism = {key = "${ETHERSCAN_API_KEY_OPTIMISM}"}

sepolia = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}", url = "https://api-holesky.etherscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
