[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
fs_permissions = [
  { access = "read-write", path = "./addresses.json" },
  { access = "read-write", path = "./out" },
  { access = "read", path = "../chainlink/config.json" },
  { access = "read", path = "../chainlink/openai" },
]

[rpc_endpoints]
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
optimism-sepolia = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base-sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

anvil = "http://127.0.0.1:8545"
